name: Bug Report
description: Report a bug with ai-nexus CLI or rules
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the bug.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this?
      placeholder: |
        1. Run `npx ai-nexus install`
        2. ...
        3. See error
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - CLI (install/update/init)
        - Semantic Router
        - Rules content
        - Cursor integration
        - Codex integration
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: ai-nexus version
      placeholder: e.g., 1.0.1 (run `npx ai-nexus --version`)

  - type: input
    id: os
    attributes:
      label: OS
      placeholder: e.g., macOS 15, Ubuntu 24.04, Windows 11
